### ISSUE TITLE
Very cool, will it be on MELPA?

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/selected.el#1]
Thx alot

seems very cool, will it be on MELPA?

thx!

z

**Comment by Kungsgeten** [comment]
Thanks! I don't know. I haven't tried to submit anything to Melpa, so I don't know how hard it is. I got informed on reddit that there's a package called region-bindings-mode, which has the same purpose, and that seems to be on Melpa.

**Comment by priyadarshan** [comment]
As far as I know `region-bindings-mode` has issues with new Emacs 25. Silex possibly fixed some in his own fork, https://github.com/Silex/region-bindings-mode, but it doesn't seem to have much development since 2014. Perhaps `selected.el` could improve on that.

To submit to Melpa is not too dificult: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md

**Comment by Kungsgeten** [comment]
I've submitted a pull request to Melpa now, so we'll see if it'll get one there!

**Comment by angrybacon** [comment]
Please do tell us (Reddit?) when it has been made available through MELPA! :)
